name = "tiny_text"
description = "Low resolution bitmap font with a small memory footprint"
version = "1.1.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "MIT"
website = ["https://github.com/JeremyGrosser/tiny_text"]
tags = ["font", "hal", "bitmap", "text"]

[[depends-on]]  # This line was added by `alr with`
hal = "*"  # This line was added by `alr with`
