name = "tiny_text"
description = "Low resolution bitmap font with a small memory footprint"
version = "1.5.1"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "MIT"
website = "https://github.com/JeremyGrosser/tiny_text"
tags = ["font", "hal", "bitmap", "text"]

[[depends-on]]
hal = "^1"
